name = "dm-broadcast-api"
main = "src/index.ts"
compatibility_date = "2026-05-30"
workers_dev = true

[vars]
CF_ACCESS_TEAM_DOMAIN = "https://magicxiaomin.cloudflareaccess.com"
CF_ACCESS_AUD = "989fa405194f68c6d93119018b92e881659ba28dafd8b4f787a8c2a02ad4d48d"

[[d1_databases]]
binding = "DB"
database_name = "dm_broadcast_mvp"
database_id = "f07a0f16-c6c9-4162-87f7-1e4a68eb9a6f"

[[kv_namespaces]]
binding = "STATE"
id = "dfa94c2504bb4beba319ef8e0062a7d5"
